import './globals.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import IconSprite from '@/components/ui/IconSprite/IconSprite';
import { ToastProvider } from '@/providers/ToastProvider';

const poppinsSans = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${poppinsSans.className}`}>
        <IconSprite />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
